### ISSUE TITLE
Support automatic closure reduction for native functions.

### ISSUE THREAD

**Issue by thantos** [functionless/functionless#122]
Support compile time reduction of closure'd references in native functions. Must consider the additional new variables in the closure and other side effects.

See https://github.com/sam-goodwin/functionless/issues/103#issuecomment-1116396779 for why this is needed.

```ts
new Function(..., () => {
   $AWS.EventBridge.putEvents(...)
})
```

becomes 

```ts
const putEvents = $AWS.EventBridge.putEvents;
new Function(..., () => {
   $AWS.EventBridge.putEvents(...);
})
```

### Harder Example

```ts
```ts
const myClassInstance = new MyClass();

new Function(..., () => {
   const myVar = myClassInstance;
   const myMethod = myVar.myMethod;

   myVar()
   myVar.myMethod()
   myMethod()
})
```
> What would the output be?

---

Caveat: References to functions in namespaces should be simplified to keep the resulting native function bundle small.

### Impacts:
1. Bundle Size
2. Invalid Bundles during tests

### Example

```ts
new Function(..., () => {
   $AWS.EventBridge.putEvents(...);
})
```

Should be

```ts
const putEvents = $AWS.EventBridge;
new Function(..., () => {
   putEvents(...);
})
```

### Reason

1. Pulumi will serialize the entirety of $AWS and all sub-variables when using the `$AWS.EventBridge.putEvents` form. 
   1. Using the referenced from has reduced bundle sizes by over 10x
2. Invalid function are created, specifically during tests, when Pulumi tries to include code generated by jest for global functions.
   1. The referenced form seems less likely to have this issue.

### Mitigation
1. Users can follow the pattern above
2. Support Automatic Reference of native integrations (future PR: )
3. Consider avoiding integrations in keep objects? `import { awsEventBridgePutEvents } from 'functionless'` instead of `import $AWS from 'functioness'` ?

_Originally posted by @thantos in https://github.com/sam-goodwin/functionless/issues/103#issuecomment-1116396779_

**Comment by sam-goodwin** [comment]
Is this still an issue?

**Comment by thantos** [comment]
No.
