### ISSUE TITLE
Remove addResolver utility from AppsyncResolver

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#137]
The `addResolver` function from an `AppsyncResolver` is an unnecessary extra step for creating a field. Instead, we should change `AppsyncResolver` to be a `Construct` whose instantiation immediately adds Resolvers to a target API.

```ts
const getPerson = new AppsyncResolver(scope, id, {
  api,
  typeName: "Query",
  fieldName: "getPerson"
}, ($context) => {
  // impl
});
```

**Comment by thantos** [comment]
From slack

> @thantos
>> if a resolver can only be added to one API (instead of an object that is latter assigned), why not wrap the API and then `.addResolver("query", "field", () => {})`

> @sam-goodwin 
>> we need to make the api consistent, Step Function and Function each are Constructs
>> .addResolver is just boilerplate

**Comment by thantos** [comment]
`Function` is actually a wrapper around a construct and not a construct itself, it could be.

What I proposed above would match event bus.

1. The `EventBus` is a construct, but wraps the `aws_events.EventBus`
2. The Functionless logic existing mostly in the `Rule` and the `Transformer` not the `EventBus`

```ts
const bus = new EventBus(this, 'bus');

// both are valid
const rule1 = bus.when(this, 'rule', () => {}); // preferred pattern
const rule2 = new EventBusRule(this, 'rule2', bus, () ={});
```

So AppSync can look like...

```ts
const api = new functionless.AppSyncApi(this, 'api', { ... schema ...  });
// or
// functionless.AppSyncApi.fromApi();

api.addResolver("Query", "name", () => {});
// or 
new functionless.AppSyncResolver("Query", "name", api, () => {});

// also - code first shema
api.addQuery("name", returnType, () => {});
```
