### ISSUE TITLE
Create Schedules on EventBus

### ISSUE THREAD

**Issue by brendo-m** [functionless/functionless#140]
`EventBus` should let you create a schedule rule. Possible syntax: `bus.every(Schedule.expression("rate(1 minute)").pipe(...)`

**Comment by thantos** [comment]
Scheduled rules only work on the default bus.

> Cannot associate rule with 'eventBus' when using 'schedule'

`EventBus.schedule().when().map().pipe();`

Or

`EventBus.default().schedule().when().map().pipe()`
