### ISSUE TITLE
Rename `EventBusRule` to `Rule`?

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#142]
EventBusRule is verbose and `Rule` seems like a primitive worthy of its own name. It looks ugly in documentation to call it `EventBusRule`.

**Comment by sam-goodwin** [comment]
Which one?

1.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/38672686/169460239-61a16926-22be-44e3-b76a-b106f4580761.png">


2. 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/38672686/169460325-df0fea64-f452-4c3c-ab82-e2c962369620.png">

**Comment by thantos** [comment]
I agree with the simpler names, at some point though we may need namespaces, for example, if any other AWS resource has a `Table` or a `Rule`.
