### ISSUE TITLE
Define convention for error code numbers

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#182]
We are defining error codes for compile and synth-time errors that are surfaced in the IDE, during `tsc` and `cdk synth`.

See: https://github.com/functionless/functionless/issues/176

Errors currently take the form: `Functionless(n)` where `n` is a numerical code. We must have a numerical error code - the language service interface provides no alternative. But we can arbitrarily choose the source prefix string, e.g. `Functionless`.

Error count has been started at 100 but with no real good reason. What convention should we follow? What does TypeScript and other compilers do?

**Comment by sam-goodwin** [comment]
Once we have defined the convention, we then need to update all of the errors. https://github.com/functionless/functionless/issues/183

**Comment by thantos** [comment]
React - https://reactjs.org/blog/2016/07/11/introducing-reacts-error-code-system.html
Typescript - https://github.com/Microsoft/TypeScript/blob/v4.7.3/src/compiler/diagnosticMessages.json
C# - https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0001
Cpp - https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/c-cpp-build-errors?view=msvc-170&viewFallbackFrom=vs-2019

From [here](https://web.eecs.umich.edu/~akamil/papers/iticse19.pdf)

* Increase Readability
* Reduce Cognitive Load
* Provide Context
* Use a Positive Tone
* Show Examples
* Show Solutions or Hints
* Allow Dynamic Interaction
* Provide Scaffolding 
* Use logical argumentation 
* Report errors at the right time 

Related
* https://people.engr.ncsu.edu/ermurph3/papers/icse17.pdf
* ![Image](https://user-images.githubusercontent.com/289213/172961294-d0439a7b-0969-4e40-9406-d213776a01a7.png)
* https://iticse19-wg10.github.io/
* https://web.eecs.umich.edu/~akamil/papers/iticse19.pdf
