### ISSUE TITLE
Secrets Manager integration

### ISSUE THREAD

**Issue by jogold** [functionless/functionless#192]
How about something like this?

```ts
interface Credentials {
  username: string,
  password: string,
}

// an existing secret stored in Secrets Manager
const secret = new Secret<Credentials>('my-secret-arn-or-name');

// 1. Secret ARN is passed as env var
// 2. IAM permissions are given to Fn
// 3. Fn gets the secret string at runtime, parses it and caches it (outside of the closure, once per container)
new Function(scope, 'Fn', async () => {
  const username = await secret.getValue().username;
  console.log('The username is: ' + username`);
});
```

Currently using a `CachedSecret` in my Lambda runtimes, but it's only part of the solution:

<details>
<summary>Code for CachedSecret</summary>
<p>

```ts
import { SecretsManager } from 'aws-sdk';
import { tryParse } from './utils';

export class CachedSecret<T> {
  private static secretsManager = new SecretsManager({ apiVersion: '2017-10-17' });

  private static cache: Map<string, any> = new Map();

  private readonly secretId: string;

  constructor(secretId: string) {
    this.secretId = secretId;
  }

  public async getValue(): Promise<T> {
    const cached = CachedSecret.cache.get(this.secretId);
    if (cached) {
      return cached;
    }

    const getSecretValue = await CachedSecret.secretsManager.getSecretValue({
      SecretId: this.secretId,
    }).promise();

    if (!getSecretValue.SecretString) {
      throw new Error('No secret string');
    }

    const parsed = tryParse<T>(getSecretValue.SecretString);
    if (!parsed) {
      throw new Error('Secret string is not JSON parsable');
    }

    CachedSecret.cache.set(this.secretId, parsed);
    return parsed;
  }
}
```

</p>
</details>

**Comment by thantos** [comment]
Thanks for the suggestion and most of the implementation @jogold. Looks like this would fit in quite nicely.

**Comment by sam-goodwin** [comment]
We should also add some documentation on how to build these types of integrations! Agree, this is something that should be added.

**Comment by sam-goodwin** [comment]
@jogold - RE: your code example, I don't think we need to use a Map to cache the secrets, do we? The `Secret` class represents a single, distinct Secret.

```ts
private static cache: Map<string, any> = new Map();
```

Also, for consistency with the rest of the framework, we should have the following:
- [ ] `functionless.ISecret<T>`
- [ ] `functionless.Secret<T>` Construct that extends the vanilla CDK's Secret class
- [ ] `functionless.ImportedSecret<T>` and `Secret.from<T>` function for importing an instance of a vanilla CDK secret.

```ts
import { Secret } from "functionless";

const secret = new Secret<T>(this, "MySecret");
const vanillaSecret = new aws_secretsmanager.Secret(this, "MySecret");
const importedSecret = Secret.from<T>(vanillaSecret);
```

**Comment by sam-goodwin** [comment]
Regarding the type:
```ts
interface Credentials {
  username: string,
  password: string,
}
```

Should we only support JSON-encoded secrets? Do we need `JsonSecret` and `StringSecret`?

**Comment by jogold** [comment]
> RE: your code example, I don't think we need to use a Map to cache the secrets, do we? The `Secret` class represents a single, distinct Secret.

Yes, this is correct, it represents a single distinct secret and conceptually I should not have a `Map`. But this way I'm sure that the cached value is always used. I'm currently passing an env var to my Lambda (`SECRET_ID`) and if I have two "operations" consuming this secret in my handler's code they can both do `new CachedSecret(process.env.SECRET_ID)` without thinking about cache issues or having to create a single `CachedSecret` and share it. It's also easier for the users of my `CachedSecret` class. I assume that the situation can/will be different here with functionless.

> Should we only support JSON-encoded secrets? Do we need `JsonSecret` and `StringSecret`?

I would go for a `json` construction prop that defaults to `true`.

**Comment by thantos** [comment]
Have you tried to front-load the secrets outside of the hander instead of on first use? 

```ts
const secretsManager = new SecretsManager({ apiVersion: '2017-10-17' });
const secrets = {
   "secretId1": secretsManager.getSecretId({ secretId: "secretId1" }).promise(),
   "secretId2": secretsManager.getSecretId({ secretId: "secretId1" }).promise(),
}

export.handler = () => {
   const secret1 = await secret["secretId1"];
}
```

and with ESM support in 14+, we can do

```ts
const secretsManager = new SecretsManager({ apiVersion: '2017-10-17' });
const secrets = {
   "secretId1": await secretsManager.getSecretId({ secretId: "secretId1" }).promise(),
   "secretId2": await secretsManager.getSecretId({ secretId: "secretId1" }).promise(),
}

export.handler = () => {
   const secret1 = secret["secretId1"];
}
```

**Comment by jogold** [comment]
> Have you tried to front-load the secrets outside of the hander instead of on first use?

Yes, I'm doing that and it's abstracted in my `CachedSecret` class (which I currently use in projects that do not use functionless). I was just explaining why I chose a `public static cache` as a `Map` instead of caching only a single value.
