### ISSUE TITLE
Error Code page Gen missing from build path

### ISSUE THREAD

**Issue by thantos** [functionless/functionless#223]
After PR #221, the error code page changed, but was not included in the self-mutation.

Likely due to prettier.

* [ ] Error code page is always up to date in PR (either self-mutation or commit hook).

**Comment by sam-goodwin** [comment]
I'd prefer to rely on local commit hook

**Comment by thantos** [comment]
After playing with this a bit, I think the best resolution is to remove the generated error-codes.md file from the source. 

This file is no different from the rest of the type docs and is in fact generated from the type docs. 

This means we'd need to ensure the type codes are also updated before updating the error codes page,  which also means running the entire site build.

Instead we should review the website output via netlify like all of the generated web pages.
