### ISSUE TITLE
Type issue in `table.query()`

### ISSUE THREAD

**Issue by volkanunsal** [functionless/functionless#226]
I noticed that there are no type hints on the `query` property on `table.query` because `RenameKeys` is called on `any` type. 

<img width="578" alt="Screen Shot 2022-06-11 at 2 11 20 PM" src="https://user-images.githubusercontent.com/151600/173200036-ea831451-4ed7-412b-9d99-bf802760f86f.png">

**Comment by thantos** [comment]
To get you unblocked:

Its using the types from `typesafe-dynamodb`: https://github.com/sam-goodwin/typesafe-dynamodb/blob/main/src/query.ts

There is an example here: https://github.com/thantos/functionless/blob/main/test/table.test.ts#L285

**Comment by thantos** [comment]
Where is that `any` coming from in `RenameFields`? I see more when there is a type in the first field.

![image](https://user-images.githubusercontent.com/289213/173200269-5bc5717d-3b0f-4d4f-9fed-2b922f5b1455.png)

**Comment by thantos** [comment]
Looks like not much shows up before you start adding properties.

![image](https://user-images.githubusercontent.com/289213/173200309-36fb258c-2d90-4e90-b785-3e29c0dc72c2.png)

**Comment by volkanunsal** [comment]
Weird... why don't I see that type hint? here is the context of that code:

```ts
const resolver = new AppsyncResolver(($context) => {
      return table.query({
        index: 'GSI1',
        query: {
          expression: ':pk = #pk',
          expressionValues: { '#pk': $context.arguments.apiKey },
          expressionNames: { ':pk': 'PK' },
        },
      });
    });
```

**Comment by volkanunsal** [comment]
Also note that I had to mark `SK` type as any because it only accepts a "PK" literal since SK type extends PK type.

**Comment by sam-goodwin** [comment]
What happens when you emit the SK type param? It defaults to undefined if I recall.

**Comment by volkanunsal** [comment]
`undefined` works, too. I figured that I might as well fill it in, though.

**Comment by volkanunsal** [comment]
This could be related. There are red line sunder the imports in the type definition file.
<img width="849" alt="Screen Shot 2022-06-11 at 2 35 17 PM 1" src="https://user-images.githubusercontent.com/151600/173200715-0bb7e55c-8e70-436c-930e-ab2ec212b9b1.png">

**Comment by sam-goodwin** [comment]
They could also be vs code doing weird things. 

Can you provide a snippet that reproduces this error? I'll take a look and try and fix.

**Comment by volkanunsal** [comment]
It looks correct. `typesafe-dynamodb` isn't in the node_modules directory -- nor the other ones.

**Comment by volkanunsal** [comment]
I fixed it by adding it to the `deps` in `.projenrc.js` file.

**Comment by sam-goodwin** [comment]
Oh interesting. Looks like we have it as a peer dependency. We should update the Functionless projen to add it.

**Comment by sam-goodwin** [comment]
> I fixed it by adding `typesafe-dynamodb` to the `deps` in `.projenrc.js` file. 

Tracking fix to projen https://github.com/functionless/functionless-projen/issues/7
