### ISSUE TITLE
Multiple calls to app.synth() breaks Function serialization

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#227]
If the CDK `app.synth()` is called twice, such as having `autoSynth:true` and then manually calling it, the Function closure serializer fails to re-bind the function body, resulting in the dummy code being deployed.

See https://github.com/functionless/functionless/issues/128#issuecomment-1153030191

**Comment by thantos** [comment]
Twice is not the problem, the problem is the first call to synth. 

Users need to use `asyncSynth()` instead of `app.synth()`

#128

**Comment by sam-goodwin** [comment]
Why? The bug in question was fixed by not calling `app.synth()` and just relying on CDK's autoSynth (which calls `app.synth()`). Why would adding `app.synth()` change that behavior?

**Comment by thantos** [comment]
`app.synth()` runs synchronously because the async function completes. autoSynth doesn't run of `app.synth()` has been run.

**Comment by thantos** [comment]
Agree with the poison pill, will add.
