### ISSUE TITLE
Nit: repo link in package.json is a link to badge.fury.io

### ISSUE THREAD

**Issue by volkanunsal** [functionless/functionless#254]
This is a minor issue, but I often use the tooltip over a dependency in `package.json` file to go to the repos of my `dependencies`. Almost every other project has a link to their repo in the hover state. However, functionless projects have a link to badge.fury.io images.

<img width="663" alt="Screen Shot 2022-06-15 at 8 40 02 PM" src="https://user-images.githubusercontent.com/151600/173965436-a03e7bec-6202-498f-ad87-04455c844cb8.png">

vs

<img width="442" alt="Screen Shot 2022-06-15 at 8 43 29 PM" src="https://user-images.githubusercontent.com/151600/173965470-72e6a6ef-e8f8-47d3-9aeb-c5ea261e1619.png">

**Comment by sam-goodwin** [comment]
Thanks for pointing this out, do you know where this information is configured?

**Comment by volkanunsal** [comment]
Hard to say. I think it might be coming from the first line of the README file. If you look at the Yarn package page of both packages, you can see the first line is the bumper in the tooltip.

https://yarnpkg.com/package/aws-cdk

https://yarnpkg.com/package/functionless

**Comment by volkanunsal** [comment]
Or maybe it's the description field of the package config....
