### ISSUE TITLE
Bug: `Function` doesn't support blockless if statements

### ISSUE THREAD

**Issue by volkanunsal** [functionless/functionless#265]
```
Error: a IfStmt's then must be a BlockStmt
```

Here is the code that produced it.

```ts
if (id && 'resolverContext' in id)
      return table.getItem({
        key: { pk: { S: `ACCOUNT#${id}` }, sk: { S: `ACCOUNT#${id}` } },
      });
```

Fixed it by adding a block after if.

**Comment by thantos** [comment]
1. `Function` doesn't support `table.getItem`, only `$AWS.DynamoDB.GetItem()`
2. `Function` is not compiled to the Functionless AST, or it shouldn't be unless something else went wrong higher up

Could you share more of the code?

**Comment by thantos** [comment]
> Error: a IfStmt's then must be a BlockStmt

I believe this is happening, will test with `StepFunction`
