### ISSUE TITLE
$util.error causes "Lexical error"

### ISSUE THREAD

**Issue by volkanunsal** [functionless/functionless#266]
Here is my code

```ts
const getAccount = new AppsyncResolver<{}, IAccount>(($context) => {
    const identity = $context.identity;

    if (identity && 'resolverContext' in identity) {
      const { accountId } = identity.resolverContext;
      return table.getItem({
        key: {
          pk: { S: `ACCOUNT#${accountId}` },
          sk: { S: `ACCOUNT#${accountId}` },
        },
      });
    }

    return $util.error('Cannot find account.');
  });
```

And this is the error:

```
[{"path":["account"],"data":null,"errorType":"MappingTemplate","errorInfo":null,"locations":[{"line":1,"column":17,"sourceName":null}],"message":"Lexical error,   Encountered: \"{\" (123), after : \".\" at *unset*[line 11, column 21]"}]
```

**Comment by sam-goodwin** [comment]
Ah this may be because we don't get support destructing syntax.

**Comment by sam-goodwin** [comment]
Potentially related: https://github.com/functionless/functionless/issues/68

**Comment by volkanunsal** [comment]
Not using destructuring takes care of that error. But `$util.error` doesn't seem to work. Instead of a custom error message, the response mapper returns a null value.

**Comment by sam-goodwin** [comment]
Ah that's interesting. It is likely the following VTl

```
#return($util.error(..))
```

I wonder if the root cause is that return swallows the error. $util.error is a void function which would explain the null.

**Comment by volkanunsal** [comment]
I tried it without return as well. Same result.
