### ISSUE TITLE
Error Code docs have h2/h3s that confuse the TOC

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#285]
Our error code docs should probably avoid using h2s and h3s because it obfuscates the TOC

![image](https://user-images.githubusercontent.com/38672686/174687614-31edb972-d540-496d-b363-27bb94e67e3c.png)

**Comment by sam-goodwin** [comment]
Also noticing that some titles are not stripping underscores
![image](https://user-images.githubusercontent.com/38672686/174687709-0bb257b5-a5e7-449e-a2ce-652efb1a7cde.png)

**Comment by sam-goodwin** [comment]
I wonder if we could alphabetically order these too?

**Comment by thantos** [comment]
I kind of want to change the error code script to use react. We'd have more control.

**Comment by sam-goodwin** [comment]
Yeah that's a good idea. For now i'm gonna release a quick clean up PR.

**Comment by sam-goodwin** [comment]
The current solution was a quick and dirty.
