### ISSUE TITLE
VariableStmt, VariableDeclarationList, VariableDeclaration

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#338]
We currently only have `VariableStmt` which can set a single variable. This is inconsistent with TS AST, where there are Variable Statements that contain a single Variable Declaration List containing many Variable Declarations.

```
VariableStatement(
  Var | Let | Const,
  VariableDeclarationList(
    ...VariableDeclaration(BindingElement, Expr)
   )
)
```

```ts
let a, b = c, d = e;
```

**Comment by thantos** [comment]
Fixed by #332
