### ISSUE TITLE
Support de-structured parameter declarations

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#364]
- [ ] Appsync VTL
- [ ] API GW VTL
- [ ] Step Function ASL
- [ ] Event Bridge
```ts
function foo({a: b = c}, [d: e = f], ...g) {}
```

**Comment by thantos** [comment]
https://github.com/functionless/functionless/issues/68

Also AppSync supports destructured (#299, #235 ) , but missed reduce I think.

https://github.com/functionless/functionless/blob/main/test/vtl.test.ts#L864
https://github.com/functionless/functionless/blob/main/test/vtl.test.ts#L898

Technically the support is in VTL, APIg may just need to be tested at runtime.

And missing a test for map/reduce.

**Comment by thantos** [comment]
also #302

**Comment by sam-goodwin** [comment]
> also #302

Ah shit. I tried to find it but didn't search "destructured". Perhaps we should start requiring keywords in issues to help with searching?
