### ISSUE TITLE
Step Functions: Support `||` and `&&` in non-condition situations. Add Boolean coercion. 

### ISSUE THREAD

**Issue by thantos** [functionless/functionless#393]
* `Boolean()` - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean/Boolean
* `||` - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR
   * Returns left if truthy, else right
   * `||` returns right when the left is falsy. `??` returns right only when the left is `undefined`.
* `&&` 
   * > More generally, the operator returns the value of the first [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) operand encountered when evaluating from left to right, or the value of the last operand if they are all [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).
* Test
  * Operator Precedence - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR#operator_precedence

**Comment by sam-goodwin** [comment]
Should we also support `??=` and `||=`?

**Comment by thantos** [comment]
and `&&=`
