### ISSUE TITLE
Step Functions: support number coercision with Number(), +<expr> and -<expr>

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#395]
- [ ] `+ <expr>` should coercse `<expr> to a number, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Unary_plus 
- [ ] `- <expr>` should coercse `<expr> to a number, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Unary_minus 
- [ ] `Number(<expr>)` should coercse `<expr.` to a number

**Comment by thantos** [comment]
Sfn supports to string... But I don't think it'll support from string to number... 

As far as I know at least, unless there is some Json path magic.
