### ISSUE TITLE
Support for typesafe SDK integrations

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [functionless/functionless#405]
It would be great to have general SDK integrations (beyond just DynamoDB and EventBridge) similar to [ts2asl](https://github.com/Stedi/ts2asl/blob/main/examples/sdk-states.md).

Maybe something like

```ts
import { S3 } from "@aws-sdk/client-s3"; // use the v2 compatible to infer types

const workflow = new StepFunction(
  this,
  "Workflow",
  async (input: Input) => {
    await $AWS.SDK(S3).getObject({
      Bucket: input.bucket,
      Key: input.key
    });
  }
);
```

the [v2 compatible style](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html#v2-compatible-style) has all functions directly on the class which would allow to infer the type

**Comment by sam-goodwin** [comment]
Thanks for the suggestion, I totally agree. We've briefly discussed this here https://github.com/functionless/functionless/issues/168.

The reason why it's not so straight-forward in Functionless is that we use these integrations to infer IAM Policy configuration, which is currently hand-written for each of the supported integrations.

Perhaps we can generate the first layer similar to ts2asl with the caveat of requiring manual IAM policy configuration.

I also wonder if we could generate the entire `$AWS.*` layer with basic IAM policy inference baked in. That would require mapping each SDK operation to an IAM Policy, which may or may not be 1:1.

**Comment by thantos** [comment]
## Inferring IAM

I don't think we NEED to infer IAM. If a non-integration is utilized to make a call, the permissions will need to be created by hand (hand == using CDK). `s3.fromArn(...).grantRead(sfn.resource)`.

## Extension and Escape Hatches.

While not 100% documented ([integrations are documented here](https://functionless.org/docs/advanced-concepts/how-integrations-work), `ASLGraph` is not documented though), it is possible make your own integrations if one does not already exist.

```ts
const myBucketS3GetObjectHook = makeIntegration<(input: { key: string }) => Promise<S3GetObjectResponse>>("My.S3.GetObject", {
   asl: (_, context) => {
       // Wire up IAM
       myBucket.grantRead(context.resource);

       // create a location for the result
       const returnVaraible = context.newHeapVariable();
       return {
          Type: "Task",
         Resource: "arn:aws:states:::aws-sdk:s3:getObject",
         Parameters: {
             "Bucket.$": myBucket.arn, // (?)
             // ... get key from args
          },
          ... task to call s3,
          ResultPath: returnVariable,
          Next: ASLGraph.DeferNext,
          output: { jsonPath: returnVariable },
       }
   }
})
```

and use

```ts
new StepFunction(stack, 'sfn', async (input) => {
   myBucketS3GetObjectHook ({ key: input.key });
})
```

Or generalized: 

```ts
const s3GetObjectHook = makeIntegration("My.S3.GetObject", {
   asl: (call, context) => {
       const bucket = // code to get bucket  from the `CallExpr` (`call`) parameter's arguments.
       // Wire up IAM
       bucket .grantRead(context.resource);

       // create a location for the result
       const returnVaraible = context.newHeapVariable();
       return {
          Type: "Task",
         Resource: "arn:aws:states:::aws-sdk:s3:getObject",
         Parameters: {
             "Bucket.$": bucket.arn // (?)
          },
          ... task to call s3,
          ResultPath: returnVariable,
          Next: ASLGraph.DeferNext,
          output: { jsonPath: returnVariable },
       }
   }
});
```

Dynamo can be used as an example: https://github.com/functionless/functionless/blob/main/src/aws.ts#L588

## Inferring from v2 or v3 SDK clients.

Something to look into, would be a natural way to generalize.

**Comment by matthias-pichler-warrify** [comment]
I think **MOST** iam actions can be inferred from the SDK method. The `aws-cdk-lib/aws-stepfunctions-tasks` package does it via an optional [`iamAction` prop](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_stepfunctions_tasks.CallAwsServiceProps.html#iamaction) where it can't.

**Comment by matthias-pichler-warrify** [comment]
@sam-goodwin Would something like this work?

```ts
// src/step-function.ts

import { FunctionKeys } from "utility-types";
import { Client as AWSClient } from "@aws-sdk/types";

export namespace $SFN {
  // ...

  type SdkIntegrationClient<T extends object> = {
    [K in FunctionKeys<T>]: T[K] extends (
      params: infer TInput,
      options: any,
      cb: (err: any, output?: infer TOutput) => void
    ) => Promise<infer _X>
      ? (input: TInput) => Promise<TOutput>
      : never;
  };

  export const sdk = <Service extends AWSClient<any, any, any>>(service: {
    prototype: Service;
    new (config: {}): Service;
  }): SdkIntegrationClient<Service> => {
    //TODO: do I need to prewarm here?
    const client = new service({});

    // TODO: add lookup for known special cases, e.g. sfn
    const [serviceName] = client.config.endpoint.hostname.split(".");

    return new Proxy(client as any, {
      get: (_, prop: string) => {
        return makeIntegration<"$AWS.SDK", (input: any) => Promise<any>>({
          kind: "$AWS.SDK",
          asl: (call, context) => {
            const input = call.args[0]?.expr;
            if (!isObjectLiteralExpr(input)) {
              throw new SynthError(
                ErrorCodes.Expected_an_object_literal,
                `First argument ('input') into $AWS.SDK must be an object.`
              );
            }

            return context.evalExpr(input, (output) => {
              if (
                !ASLGraph.isLiteralValue(output) ||
                typeof output.value !== "object" ||
                !output.value
              ) {
                throw new SynthError(
                  ErrorCodes.Unexpected_Error,
                  "Expected an object literal as the first parameter."
                );
              }

              return context.stateWithHeapOutput({
                Type: "Task",
                Resource: `arn:aws:states:::aws-sdk:${serviceName}:${prop}`,
                Parameters: output.value,
                Next: ASLGraph.DeferNext,
              });
            });
          },
        });
      },
    });
  };
}
```

These are the editor suggestions I am getting:

![Screen Shot 2022-08-11 at 13 35 39](https://user-images.githubusercontent.com/48183213/184124842-188c06df-f9eb-4100-aacc-7bf298763a6c.png)

![Screen Shot 2022-08-11 at 13 34 54](https://user-images.githubusercontent.com/48183213/184124867-9e30cbe9-0220-47cc-8115-d66ef921d735.png)

```ts

import { CloudWatch } from "@aws-sdk/client-cloudwatch";

ExpressStepFunction(stack, "fn", (): string | void => {
  $SFN.sdk(CloudWatch).describeAlarms({});
});
```

**Comment by sam-goodwin** [comment]
@matthias-pichler-warrify this looks fantastic! I think it could be a great way to add support for all of the AWS SDK integrations, even if it doesn't have IAM inference for now. Thanks for putting it together.

Do you mind opening up a PR so we can provide feedback. There are some things we can optimize/change before merging it in.

For example: I'm not sure `$SFN.sdk(CloudWatch)` being called within a Step Function will work as our interpreter will assume it's an API call. We could add a special handler for that or we could design it to be more static.

```ts
$SFN.SDK.CloudWatch
```

We can still use the same `Proxy` utility.

```ts
import AWS from "aws-sdk";

export namespace $SFN {
  export const SDK: {
     [serviceName in keyof typeof AWS]: InstanceType<(typeof AWS)[serviceName]>
  } = new Proxy({}, {
     get: ..
  }) 
}
```

Also, we are planning to remove `$SFN` in favor of placing the helpers on `StepFunction` instead.

**Comment by sam-goodwin** [comment]
Oh and by the way - super clever solution with the Proxy. Nice job.

**Comment by thantos** [comment]
+1 Great work, looking forwards to participating on this PR.

We could also statically generate the clients using the models instead of relying on the SDK.

Here are the smithy models.

https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models

**Comment by sam-goodwin** [comment]
Do those models have any IAM Policy information?

**Comment by thantos** [comment]
It does not

**Comment by thantos** [comment]
Need to find a consumable version of this:

https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html

**Comment by thantos** [comment]
Some may have them, there is a trait for it
https://awslabs.github.io/smithy/2.0/aws/aws-iam.html#aws-iam-requiredactions-trait

**Comment by thantos** [comment]
yep

https://github.com/aws/aws-sdk-go-v2/blob/9fa6b960d598b691af70ce3fc37c50c74aa8b368/codegen/sdk-codegen/aws-models/amplifyuibuilder.json#L855

**Comment by matthias-pichler-warrify** [comment]
@sam-goodwin Thanks for the feedback. I'll open a PR soon 👍

Regarding your comment:
> For example: I'm not sure $SFN.sdk(CloudWatch) being called within a Step Function will work as our interpreter will assume it's an API call. We could add a special handler for that or we could design it to be more static.

Currently that wouldn't work because I am using the AWS JavaScript SDK v3 where every client is in a different package. (e.g. `@aws-sdk/client-s3`) I couldn't get the types working with the sdk v2 because of the overloads: every method on every client ist overloaded (something like) with

```ts
namespace AWS {
  //...
  namespace S3 {
    //...
    getObject: (cb?: (err?: AWSError, data: GetObjectOutput) => void)) => Request<GetObjectOutput>;
   
    getObject: (params: GetObjectInput, cb?: (err?: AWSError, data: GetObjectOutput) => void)) => Request<GetObjectOutput>;
  }
}
```

And my TS skills couldn't get me past that. If you have a way to get around that, that would be great 🙏. I'll share my failed approach tomorrow.

**Comment by thantos** [comment]
If @sam-goodwin cannot get something working in TS it isn't possible.

I believe we should be able to pattern match the interfaces to find the one without the callback.

**Comment by matthias-pichler-warrify** [comment]
> ```
> import AWS from "aws-sdk";
>
> export namespace $SFN {
>  export const SDK: {
>     [serviceName in keyof typeof AWS]: InstanceType<(typeof AWS)[serviceName]>
>  } = new Proxy({}, {
>     get: ..
>  }) 
> }
> ```

this was absolutely brilliant from you @sam-goodwin. I got the types working now:

![Screen Shot 2022-08-12 at 11 29 26](https://user-images.githubusercontent.com/48183213/184330337-1994c2d6-cf78-4bc0-9415-d53ffcf56e47.png)

![Screen Shot 2022-08-12 at 11 30 10](https://user-images.githubusercontent.com/48183213/184330363-363dff79-2503-4738-a521-a8c9a93e86f3.png)

Feedback on the PR #414 is super welcome. It's still missing IAM permissions and test.

**Comment by sam-goodwin** [comment]
@matthias-pichler-warrify I think those types require `.promise()`. I've been playing with the types and also noticed that aws-sdk v2 has the problem of function overloads when inferring types.

**Comment by sam-goodwin** [comment]
> Feedback on the PR https://github.com/functionless/functionless/pull/414 is super welcome. It's still missing IAM permissions and test.

Am looking - trying to think about how to do the types.

**Comment by sam-goodwin** [comment]
Are we OK with the DX being:

```ts
const item = await $SFN.SDK.DynamoDB.getItem({
  ...
}).promise()
```

**Comment by sam-goodwin** [comment]
> yep
> 
> https://github.com/aws/aws-sdk-go-v2/blob/9fa6b960d598b691af70ce3fc37c50c74aa8b368/codegen/sdk-codegen/aws-models/amplifyuibuilder.json#L855

Where does the spec originate from?

**Comment by sam-goodwin** [comment]
> > yep
> > https://github.com/aws/aws-sdk-go-v2/blob/9fa6b960d598b691af70ce3fc37c50c74aa8b368/codegen/sdk-codegen/aws-models/amplifyuibuilder.json#L855
> 
> Where does the spec originate from?

I found this https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models

**Comment by matthias-pichler-warrify** [comment]
> Are we OK with the DX being:
>
>const item = await $SFN.SDK.DynamoDB.getItem({
>  ...
>}).promise()

I mean I would prefer not having that, but I currently don't see how. Does the `.promise()` access mess with the ASL parsing?

> > > yep
> > > https://github.com/aws/aws-sdk-go-v2/blob/9fa6b960d598b691af70ce3fc37c50c74aa8b368/codegen/sdk-codegen/aws-models/amplifyuibuilder.json#L855
> >
> > Where does the spec originate from?
>
> I found this https://github.com/aws/aws-sdk-js-v3/tree/main/codegen/sdk-codegen/aws-models

It seems to me that these only contain the IAM actions that are required "indirectly" (e.g. in amplifyuibuilder `DeleteComponent` specifies `amplify:GetApp`). The other permissions we would need to infer from the api call (which should be possible since they are identical in most cases). Nevertheless the resources can't be inferred.

**Comment by sam-goodwin** [comment]
> Does the .promise() access mess with the ASL parsing?

We can make it work, but would prefer not. Seems the options are:
1. `$SFN.SDK(DynamoDB).getItem`
2. `$SFN.DynamoDB.getItem(..).promise()`
3. generate some types from the spec

**Comment by sam-goodwin** [comment]
> Still the iam resources can't be inferred, so we need to pass these along. I was thinking of something like
> 
> ```ts
> $SFN.SDK.CloudWatch.describeAlarms({/*params*/}, { 
>   iamResources: ["arn:aws:..."], // required
>   iamActions: ["cloudwatch:DescribeAlarms"] // optional, inferred from the api call
> })
> ```

I like the escape hatch, we should always have those.

**Comment by matthias-pichler-warrify** [comment]
> > Does the .promise() access mess with the ASL parsing?
> 
> We can make it work, but would prefer not. Seems the options are:
> 
> 1. `$SFN.SDK(DynamoDB).getItem`
> 2. `$SFN.DynamoDB.getItem(..).promise()`
> 3. generate some types from the spec

2. would be `$SFN.SDK.DynamoDB.getItem(..).promise()`

is there really no way to infer the parameters from overloaded functions?

**Comment by sam-goodwin** [comment]
> is there really no way to infer the parameters from overloaded functions?

I don't believe it's possible to reverse an intersection type into its components. I tried some things, maybe there is a way?

Code generation might be worth a shot. Can we loop through all the @aws-sdk/client-* packages and generate a small typescript file that imports the types and exports a namespace?

**Comment by matthias-pichler-warrify** [comment]
> > is there really no way to infer the parameters from overloaded functions?
> 
> I don't believe it's possible to reverse an intersection type into its components. I tried some things, maybe there is a way?

this [Typescript Playground](https://www.typescriptlang.org/play?ts=4.7.2#code/C4TwDgpgBA+g8gNwgJwDYHsCGATAqgOwEt18AeAFURQxwBopyAFTZYQzVKtLbKAXigBXfAGt86AO74AfPwbNW7Tkm44oAMgZcavCAA9gEfNgDOUABQBYAFBQoAOkcsA5iYBcUQvgBmKBgEFkVxsASn5ZL19kBgAlCGBBZHwbOwB+KAB6DKhGZAgkfGBPHy9CQyg8gGNEk2J8KAAjECgTYHQwMC9nCohq5FqSKAkACyN5FjYObR4Uu0zs4cwzTErqgFtBVExDXg5UKHRvKGBRrRUdFsJnfG3EiBN7WbsmCaVptX1DYzNKc5nbObpfD5FBPKBuMFzKAAH1g7zwRBIFHh9EYhEqImRfzoUBEEBAhzO1B4sk0L0UU2xvE05nMjnsLncASCJjCfFk5DiCSSIWkkLmsNp9MZHnIgVcbI5XMS+BCsw8wJUAG4bDZQJAoPCCHUscSPgYjKYLMKWR5MPgQABtAC6kqg5pAsgEAFE9JVUIJsBBSLN4FTtUiwVkGKcAETmO2KlChy7XW55KAbVqNaDDdCEVoQXhtY5h7zIEjAGOEk4QIPZLyGfq9NgkejedDRYASdA9JYkJmYMINXqYQQmaBVGp1FptMBmEZjMqeEzlqBGSroYRVrP0c28BphacDiBrMw5sB5ApFUtQReoLbj6CEkyCBoDgCOgiMwDnocXazA20IDVQEBjtRxty9wWBAzj2FA4Z2gg6bYDGlatuGmCpB4ACM0GwaGIS0HOIzosMUDOIQSDLFA2CEFURSLvgKgDPUOaYEIiL4I8AJ2LSkYgsgYRkvCszSDhAK-HqugGt8FicSoUBAlx4ISeEUBRsgNjSCq1g2BkABUNjkKcwDIOiIj7q2p6YA06BID0fR0faeT0qq1hdlAACSPgoAZ+DdKeX7IJgazxH4649Ny9HgCBhLmgcVJZlA3jCJUtb1BIhAXkIA5qqcWzJhZImxjcwH0HhlQERm9odCwL6oM0kX6GAqDotOXqAfUxXppUECsTYm4uYUKADglXT2pcnl-nl8bQMlJy5teBlETc+yVn1NZ1PQlSRXkjZesp1inot1YDYM5hgOgJi1L+1X1MI2DoOsL4xbUXrzt4vgJakISddYlRhK5Vb9YlZhrfUJBVSmPQALSbSgq6KegRQ3MgBYSDF5h5Nggjtdg2FQAAyug9CljYe1-SOizGaDeQNIIKVFF402QeSkzKCJMbOEYKDovjozJNYQ79COgOg607SQLwk70accWpUTy2DKTKZjBTVOoMArFwKWyDJQOnOlS2my8Hkt7K8U9r1JEpTlLzdGsZpGQOcGzp3CImAAIRqmFDD3MA-ioXIWrMaQADeswRh4MGENganschaEhGhkcWJgHgAEz0A0yex1ASdqQAvqpdvZM62Cs1AADCSwQB4UEKUpAFXPldyJv2RQ9lAaYZjsrHqtA5Ce-4Se+-6-tBwCIdQGHEfB9HUDoXHk-J6n6fJ-Ho9KTnefqdY9tF9AZcDh4AAigh1ei2zQM143LAm6BrGUHduxqPetP4ADMA8iQGZDD+xGfj8vU8z9PZeP9YJKnmGRI+9U1qGDnpnBemcM5Z0nihaeGdUKgODGjY+UCyzWFzmpDS2QABysNoAnG2HTSG0RCQ5VUEaUqaxMCVkYcCXgtNTzCBWkMYY+FEwQHNLOTe2QyE02AAAcjMEePqP5Rr9kGoxD+5B0A-SWgdUKGpJwJlPDQnQBCDjIC2ombYv0IK6WgPodqYBEozkghGauXFQyFW4cVVuSxjithbm3TM2BdE5lPPmQsBwji7V6vtRKEEAASkguL0DKOIumawTpFBMJASohBvDojGgVXRRUCL+X4a3dMrRBrbjTHrQWmBfCeCCacDhgxSrURUDsRoKwRBuJNro6WqiPrBlclEDy3RGK1KBkcHyfkApNggeFaIeQQrHDCmYUq4gJBQGOqdaRHV77QHhAoMZv0KDzjEkaOkThTQmytLaBSDonQ5BYLsvqpA-Y6nINIdeXdNRUmlEkcgYV9mfENGYY5DJTkOhtHaK5chPn4G+ZAB5g8nkvPwTtd2j9gAACEfYCG2bc-yeyv4SVDiApBMdZ4j0TrAxoi9M5AIVFxNeiK3kotRf3TFHz4gymhd6PFo9f5EpQSSqO88KXwKXsHDOq8bB4PzlAYh5RTyhhrsFGUcyNSA1Ec3aAXh3Semhj2Na-ZoBDInGUAiSldHXRhjTfAWrHplFYkAA) seems to have found a way 🤔

**Comment by sam-goodwin** [comment]
Oh nice, well with that we can now do it!

```ts
import AWS from "aws-sdk";

type _OverloadUnion<TOverload, TPartialOverload = unknown> = TPartialOverload &
  TOverload extends (...args: infer TArgs) => infer TReturn
  ? // Prevent infinite recursion by stopping recursion when TPartialOverload
    // has accumulated all of the TOverload signatures.
    TPartialOverload extends TOverload
    ? never
    :
        | _OverloadUnion<
            TOverload,
            Pick<TOverload, keyof TOverload> &
              TPartialOverload &
              ((...args: TArgs) => TReturn)
          >
        | ((...args: TArgs) => TReturn)
  : never;

type OverloadUnion<TOverload extends (...args: any[]) => any> = Exclude<
  _OverloadUnion<
    // The "() => never" signature must be hoisted to the "front" of the
    // intersection, for two reasons: a) because recursion stops when it is
    // encountered, and b) it seems to prevent the collapse of subsequent
    // "compatible" signatures (eg. "() => void" into "(a?: 1) => void"),
    // which gives a direct conversion to a union.
    (() => never) & TOverload
  >,
  TOverload extends () => never ? never : () => never
>;

type StepFunctionSDK = {
  [serviceName in keyof typeof AWS]: typeof AWS[serviceName] extends new (
    ...args: any[]
  ) => infer Client
    ? {
        [methodName in keyof Client]: StepFunctionMethod<Client[methodName]>;
      }
    : never;
};

type StepFunctionMethod<API> = API extends (...args: any[]) => any
  ? Exclude<OverloadUnion<API>, (cb: (...args: any[]) => any) => any> extends (
      input: infer Input extends {}
    ) => AWS.Request<infer Output, any>
    ? (input: Input) => Output
    : never
  : never;

declare const sdk: StepFunctionSDK;
sdk.DynamoDB.getItem({
  
});

```

**Comment by sam-goodwin** [comment]
> this [Typescript Playground](https://www.typescriptlang.org/play?ts=4.7.2#code/C4TwDgpgBA+g8gNwgJwDYHsCGATAqgOwEt18AeAFURQxwBopyAFTZYQzVKtLbKAXigBXfAGt86AO74AfPwbNW7Tkm44oAMgZcavCAA9gEfNgDOUABQBYAFBQoAOkcsA5iYBcUQvgBmKBgEFkVxsASn5ZL19kBgAlCGBBZHwbOwB+KAB6DKhGZAgkfGBPHy9CQyg8gGNEk2J8KAAjECgTYHQwMC9nCohq5FqSKAkACyN5FjYObR4Uu0zs4cwzTErqgFtBVExDXg5UKHRvKGBRrRUdFsJnfG3EiBN7WbsmCaVptX1DYzNKc5nbObpfD5FBPKBuMFzKAAH1g7zwRBIFHh9EYhEqImRfzoUBEEBAhzO1B4sk0L0UU2xvE05nMjnsLncASCJjCfFk5DiCSSIWkkLmsNp9MZHnIgVcbI5XMS+BCsw8wJUAG4bDZQJAoPCCHUscSPgYjKYLMKWR5MPgQABtAC6kqg5pAsgEAFE9JVUIJsBBSLN4FTtUiwVkGKcAETmO2KlChy7XW55KAbVqNaDDdCEVoQXhtY5h7zIEjAGOEk4QIPZLyGfq9NgkejedDRYASdA9JYkJmYMINXqYQQmaBVGp1FptMBmEZjMqeEzlqBGSroYRVrP0c28BphacDiBrMw5sB5ApFUtQReoLbj6CEkyCBoDgCOgiMwDnocXazA20IDVQEBjtRxty9wWBAzj2FA4Z2gg6bYDGlatuGmCpB4ACM0GwaGIS0HOIzosMUDOIQSDLFA2CEFURSLvgKgDPUOaYEIiL4I8AJ2LSkYgsgYRkvCszSDhAK-HqugGt8FicSoUBAlx4ISeEUBRsgNjSCq1g2BkABUNjkKcwDIOiIj7q2p6YA06BID0fR0faeT0qq1hdlAACSPgoAZ+DdKeX7IJgazxH4649Ny9HgCBhLmgcVJZlA3jCJUtb1BIhAXkIA5qqcWzJhZImxjcwH0HhlQERm9odCwL6oM0kX6GAqDotOXqAfUxXppUECsTYm4uYUKADglXT2pcnl-nl8bQMlJy5teBlETc+yVn1NZ1PQlSRXkjZesp1inot1YDYM5hgOgJi1L+1X1MI2DoOsL4xbUXrzt4vgJakISddYlRhK5Vb9YlZhrfUJBVSmPQALSbSgq6KegRQ3MgBYSDF5h5Nggjtdg2FQAAyug9CljYe1-SOizGaDeQNIIKVFF402QeSkzKCJMbOEYKDovjozJNYQ79COgOg607SQLwk70accWpUTy2DKTKZjBTVOoMArFwKWyDJQOnOlS2my8Hkt7K8U9r1JEpTlLzdGsZpGQOcGzp3CImAAIRqmFDD3MA-ioXIWrMaQADeswRh4MGENganschaEhGhkcWJgHgAEz0A0yex1ASdqQAvqpdvZM62Cs1AADCSwQB4UEKUpAFXPldyJv2RQ9lAaYZjsrHqtA5Ce-4Se+-6-tBwCIdQGHEfB9HUDoXHk-J6n6fJ-Ho9KTnefqdY9tF9AZcDh4AAigh1ei2zQM143LAm6BrGUHduxqPetP4ADMA8iQGZDD+xGfj8vU8z9PZeP9YJKnmGRI+9U1qGDnpnBemcM5Z0nihaeGdUKgODGjY+UCyzWFzmpDS2QABysNoAnG2HTSG0RCQ5VUEaUqaxMCVkYcCXgtNTzCBWkMYY+FEwQHNLOTe2QyE02AAAcjMEePqP5Rr9kGoxD+5B0A-SWgdUKGpJwJlPDQnQBCDjIC2ombYv0IK6WgPodqYBEozkghGauXFQyFW4cVVuSxjithbm3TM2BdE5lPPmQsBwji7V6vtRKEEAASkguL0DKOIumawTpFBMJASohBvDojGgVXRRUCL+X4a3dMrRBrbjTHrQWmBfCeCCacDhgxSrURUDsRoKwRBuJNro6WqiPrBlclEDy3RGK1KBkcHyfkApNggeFaIeQQrHDCmYUq4gJBQGOqdaRHV77QHhAoMZv0KDzjEkaOkThTQmytLaBSDonQ5BYLsvqpA-Y6nINIdeXdNRUmlEkcgYV9mfENGYY5DJTkOhtHaK5chPn4G+ZAB5g8nkvPwTtd2j9gAACEfYCG2bc-yeyv4SVDiApBMdZ4j0TrAxoi9M5AIVFxNeiK3kotRf3TFHz4gymhd6PFo9f5EpQSSqO88KXwKXsHDOq8bB4PzlAYh5RTyhhrsFGUcyNSA1Ec3aAXh3Semhj2Na-ZoBDInGUAiSldHXRhjTfAWrHplFYkAA) seems to have found a way 🤔

Amazing whoever did this.
