### ISSUE TITLE
Event Sources

### ISSUE THREAD

**Issue by thantos** [functionless/functionless#44]
Add auto event bus rule generation from integrations with the ability.

Some AWS services like Lambda, Step Functions, and more automatically generate Rules on the default bus.

Add the ability to automatically create these rules and then send to all Functionless Event Bus target. They should support type safe event types based on the event.

```ts
myFunction.onSucccess().send(myMachine, event => event.detail.result);
myMachine.onStarted().send(...)
```

Where `send` is the outcome of #37 's final target design.

**Comment by sam-goodwin** [comment]
Love it! Are the event types user defined at all or static definitions from AWS?

**Comment by thantos** [comment]
It will be based on the integration, which is why I showed them as methods, some might be a template and some may be static. Probably need some rule generation logic as well like `myFunction.onSuccess().when(event => "user" in event.result)`
