### ISSUE TITLE
Checking that a value is undefined and/or using the not operator does not translate to correct ASL

### ISSUE THREAD

**Issue by tvanhens** [functionless/functionless#442]
Example:

![image](https://user-images.githubusercontent.com/5342795/186773158-4d3f836c-cc08-4b28-a5e5-b960f57167af.png)

I would expect `connections.Items` to return `false` and not follow the return branch when `connections.Items` contains a valid array. However, when `connections.Items` is set, the step function follows the `true` branch.

Input to Step:

![image](https://user-images.githubusercontent.com/5342795/186773499-358f4dab-8f13-4053-9863-cca8731698a0.png)

Generated ASL:

```
    "if(connections.Items == undefined)": {
      "Type": "Choice",
      "Choices": [
        {
          "And": [
            {
              "IsPresent": true,
              "Variable": "$.connections.Items"
            },
            {
              "IsNull": false,
              "Variable": "$$.Execution.Id"
            }
          ],
          "Next": "return"
        }
      ],
      "Default": "for(item of connections.Items)"
    },
```

**Comment by tvanhens** [comment]
This does work if I use `if (connections.Items == null)` as a workaround.

It does not work when I use `if (!connections.Items)`.

I would expect all 3 to behave the same based on the behavior in javascript.

**Comment by thantos** [comment]
Interesting, didn't realize that `==` and `===` behave differently here.

```ts
const items = null
items === undefined //false
items === null // true
!items // true
items == undefined // true
items == null // true


const items2 = undefined
items === undefined // true
items === null // false
!items // true
items == undefined // true
items == null // true
```

![image](https://user-images.githubusercontent.com/289213/186775171-b9b7109a-57fa-44cb-a160-e91031302fb3.png)

Think I see the issue, will fix.

**Comment by tvanhens** [comment]
I also tried with `=== undefined` which didn't work either. I switched to the double equals syntax after looking at the functionless docs. JavaScript isn't exactly the best role model when it comes to value comparison lol

**Comment by thantos** [comment]
it isn't...

Thoughts on what to do with `==` between number and string?

https://262.ecma-international.org/5.1/#sec-11.9.3

> return the result of the comparison [ToNumber](https://262.ecma-international.org/5.1/#sec-9.3)(x) == y

Step Functions cannot convert a string to a number.

**Comment by tvanhens** [comment]
:grimacing:

I thought there was a way to do that roughly with intrinsic functions e.g. `States.JsonToString`?

Maybe its too disgusting but you could go the other way to get roughly the same thing:

`States.JsonToString(num_value) == string_value`

Otherwise I would say making the comparison illegal via your language service since it could lead to non-intuitive outcomes.

**Comment by sam-goodwin** [comment]
StringToJson will convert to number provided there are no quotes right? A digit is a valid json expression

**Comment by tvanhens** [comment]
Yeah that should work. I don't know why I forgot about the reverse operation lol

**Comment by thantos** [comment]
Good idea. We can use that to implement `Number()`.

`==` will be more complex without synth time types. The algorithm depends on `Type()` in JS. We'll need to inject some nodes to create the correct logic.

**Comment by sam-goodwin** [comment]
> Good idea. We can use that to implement `Number()`.
> 
> 
> 
> `==` will be more complex without synth time types. The algorithm depends on `Type()` in JS. We'll need to inject some nodes to create the correct logic.

Need a Choice state with `IsNumeric` and unfortunate added transition cost.

**Comment by thantos** [comment]
isNumeric, isBoolean, isNull, isNotPresent, and the fallback to isObject.

One option is to use the typeof logic to output the types of each side and then decide how to compare. 

Probably some optimization here as well.

**Comment by tvanhens** [comment]
I'm a bit naive on what is feasible to do with the language server, but I'm wondering if it might be better to limit surface area and not support https://262.ecma-international.org/5.1/#sec-11.9.3 explicitly for the time-being.

As far as I'm aware, the triple syntax is best practice anyways. If the language server could detect usage of `==`, `!=`, etc. in a `StepFunction` context and relay a helpful error message, that might be a better solution.

**Comment by thantos** [comment]
We could emit an error or warning when `==` is used. Was thinking about that too. No matter what, the `==` will be less efficient and its unlikely someone should need it's weird logic if we expose `Number()` and `String()` (already have `Boolean()`) #446

**Comment by thantos** [comment]
@tvanhens you can try `=== undefined` now once 0.21.19 releases.

The other issues have moved to other tickets. #445 #446
