### ISSUE TITLE
Support explicit `register` hook for functionless

### ISSUE THREAD

**Issue by tvanhens** [functionless/functionless#480]
Functionless currently requires `swc` for compilation. Specifically, functionless has a dependency on our [ast-reflection][1] plugin for `swc` to inject and transform an AST as metadata onto every closure. Without this plugin, most of the features within Functionless will not work properly.

The burden of configuring this compilation step is placed on the user. To make it easier, we've codified the configuration in our [projen template][2]. However, projen is a heavy opinion to impose on our users. For example, prone completely takes over dependency management for projects and does not allow users to manage their dependencies in the ways they are already familiar with (such as using `npm i <dep>`).

In spite of its downsides, projen has provided at least one major value for consumers: the ability to upgrade the configuration as functionless evolves its configuration requirements. We're currently working on a new getting started template that does not impose as strict constraints on the user, but without addressing the configuration problem, it runs the risk of users not being able to stay up-to-date on the latest configuration requirements as the project evolves.

To address this, functionless should expose its own `register` hook. This would allow us to supply the proper configuration to any required hooks, and let users depend on one consistent compilation hook when configuring their project. This would replace the current [`@swc/register`][3] hook in the `app.json` config of consumer projects.

The plan is to replace `@swc/register` with `functionless/lib/register` in `app.json` in the new functionless template.

The following steps are required:
- [x] Add a register module to the functionless repo that sets up `@swc/register` transparently with the proper configuration.
- [x] Update the creation template to use `functionless/register`.
- [x] Add a loader module to the functionless repo to support testing. Model after [swc-loader][4].
- [x] Update the creation template to use `functionless/loader`.

[1]: https://github.com/functionless/ast-reflection
[2]: https://github.com/functionless/functionless-projen/blob/main/src/component.ts#L116-L118
[3]: https://github.com/functionless/functionless-projen/blob/main/src/project.ts#L21
[4]: https://github.com/swc-project/swc-loader/blob/master/src/index.js

**Comment by sam-goodwin** [comment]
Perhaps `functionless/register` instead of the `lib`

**Comment by tvanhens** [comment]
> Perhaps `functionless/register` instead of the `lib`

This is what I originally wanted but I'm not sure how to reconcile this with how the project is currently packaged in the lib director.

**Comment by sam-goodwin** [comment]
> > Perhaps `functionless/register` instead of the `lib`
> 
> This is what I originally wanted but I'm not sure how to reconcile this with how the project is currently packaged in the lib director.

I'm pretty sure that is only true when importing the `"functionless"` - which refers to the `package.json/main` property. If you import a file directly, you have access to the root folder of the package.

We should verify, but i think this is how it works.
```ts
// "node_modules/functionless/lib/index.ts" because of package.json/main
import "functionless";

// "node_modules/functionless/register.js"
import "functionless/register" 
```

**Comment by tvanhens** [comment]
Just tried this and it fails due to being unable to find the module. There has to be a way to make it work though. Probably some other config in the `package.json`. I'll keep digging since I think it looks much cleaner without the lib.

**Comment by sam-goodwin** [comment]
Is it included in the tgz?

**Comment by tvanhens** [comment]
Yeah it is but its in the lib directory. For some reason node doesn't seem to treat the main entrypoint as the root when resolving nested files, it treats the package.json location as the root.

**Comment by sam-goodwin** [comment]
> Yeah it is but its in the lib directory. For some reason node doesn't seem to treat the main entrypoint as the root when resolving nested files, it treats the package.json location as the root.

Move it to the root and it'll work. 

functionless/register.js

**Comment by sam-goodwin** [comment]
The only special case is when importing the module by name. All other file references start from the root. `main` only affects the default import.
