### ISSUE TITLE
Step Functions: Retry

### ISSUE THREAD

**Issue by thantos** [functionless/functionless#486]
```ts
$SFN.retry(async () => {
   ....
})
```

Will create a parallel task with a single branch.

Limits:

1. Cannot update mutable variables outside of the parallel/retry, like the `$SFN.map` and `$SFN.parallel` functions.
2. will re-run any of the expressions in the parallel, adding some cost over just retrying the task.

**Comment by sam-goodwin** [comment]
Why paralllel? Can we not push down the catches onto the subsequent states?

**Comment by thantos** [comment]
Currently we are using the built in retry and not catch. This enables built in exponential backoff and only counts as one state.

### Using Parallel with Retry

This is a common strategy, as @tvanhens mentioned, he also used it to implement retry over an arbitrary block of states.

Limits
1. Mutable variables are more difficult to implement.

### Pushing Retry down to the states

The retry limit would be restart for each state

```ts
$SFN.retry(() => { func1(); func2() })
```

This would retry both functions up to 3 times for any error, while the current contract is to retry the whole block up to 3 times.

### Implementing our own Retry

Would require multiple extra states

task -> catch -> increment attempts -> check attempts -> wait -> task.

Limits:
1. backoff cannot be a fraction
2. 4 extra transitions
3. Adds extra data to the state.

I kind of like this option except for the backoff limit.
