### ISSUE TITLE
Step Functions: Conditional Expressions 

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#56]
Support Conditional Expressions in Step Functions, we currently throw an error.

```ts
return taskA() ? taskB() : constant.
```

**Comment by sam-goodwin** [comment]
@thantos was this fixed in https://github.com/functionless/functionless/pull/280?

**Comment by thantos** [comment]
It wasn't , but I did make a duplicate ticket...

**Comment by sam-goodwin** [comment]
Closing in favor of https://github.com/functionless/functionless/issues/281
