### ISSUE TITLE
Is functionless still alive

### ISSUE THREAD

**Issue by MaazDev** [functionless/functionless#574]
Dear maintainers of functionless ,

I hope this message finds you well. I was wondering if the functionless package is still being supported. It's been several months since the last commit to the repository, and I wanted to check if the package is still being maintained.

Thank you for your time and any information you can provide.

**Comment by sam-goodwin** [comment]
Hi @MaazDev, thanks for reaching out and for your interest in functionless. We're not actively working on the project at this time. Given feedback, we decided to double down on a more narrow approach that is not coupled to AWS or the AWS CDK. It is similar in theme and industry. If you'd like, I'd be happy to meet with you to provide a demo. We're just about to start running a beta of the new project so if that's something that interests you, let's connect.

**Comment by MaazDev** [comment]
Thanks for getting back to me and for letting me know what's going on with functionless. I appreciate the offer to meet and see a demo of the new project, but I'm just working on personal projects right now and don't have a company to use it for. No worries though! I hope the new project goes well and wish you all the best. Thanks again for taking the time to respond.

**Comment by robert-lemmens** [comment]
Hello, I've also been eyeing functionless for a while - sad to see it be deprecated, but somewhat interested in what you are working on now. Is it an open source project, similar to functionless in design goals?

We have many step functions and the stringly typed system that functionless solved is what we are looking for.

**Comment by sam-goodwin** [comment]
Hi @robert-lemmens, I am working on an open source project that has similar goals but a slightly different approach. If you found Functionless interesting, you might be interested in our new project. Let me know if you'd like to chat about it!

**Comment by robert-lemmens** [comment]
hi @sam-goodwin, I might be, it all depends.  Is there anywhere i can find some information on your new project?
