### ISSUE TITLE
SQS Queue type-safe integration class

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#58]
Provide a wrapper class, `Queue<T>`, that models the SQS Queue Functionless integrations.

Must integrates with the following:

1. AppSync
```ts
const queue = new Queue<string>(new aws_sqs.Queue(..))

new AppsyncResolver<{id: string}>($context => {
  queue.sendMessage({
     MessageBody: id,
     MessageAttributes: ..
  });
});
```

2. Step Functions

```ts
new StepFunction(scope, id, (id: string) => {
  queue.sendMessage({
     MessageBody: id,
     MessageAttributes: ..
  })
})
```

3. Event Bridge
```ts
bus
  .when(scope, "rule", event => event.source === "lambda")
  .map(event => event.message)
  .pipe(queue)
```

4. Lambda
```ts
new Function(scope, id, async () => {
  await queue.sendMessage(..);
});
```

**Comment by sam-goodwin** [comment]
How should we go about layering this?

1. L1 `Queue` - no type information, all APIs use the vanilla AWS SDK APIs, e.g. `MessageBody: string`
2. L2 `Queue<T>` - captures type information and provides serialization/deserialization utility?

For supporting an arbitrary `T`, we will need some `Codec<T>` type that encapsulates serialization/deserialization logic.

```ts
export interface ReadCodec<Value, Data> {
  read(data: Data): Value;
}
export interface WriteCodec<Value, Data> {
  write(value: Value): Data;
}
export interface Codec<Value, Data>
  extends ReadCodec<Value, Data>,
    WriteCodec<Value, Data> {}

export class JsonCodec<T> implements Codec<T, string> {
  public read(data: string): T {
    return JSON.parse(data);
  }
  public write(value: T): string {
    return JSON.stringify(value);
  }
}
```

**Comment by thantos** [comment]
Could we do the same contract as secret?

Textqueue and jsonqueue?

Roll parse into the integration?

**Comment by sam-goodwin** [comment]
> Could we do the same contract as secret?
> 
> Textqueue and jsonqueue?
> 
> Roll parse into the integration?

I was thinking the same, although we may need to consider cases like Avro, ProtoBuf, Flatbuffers, etc. So i was wondering if we could have a Codec abstraction - quickly run into limitations with closure serialization and `this` though.

**Comment by sam-goodwin** [comment]
That said, JsonSecret likely covers 99% of cases ha

**Comment by thantos** [comment]
Keep it simple? Anyone can make another overload and more l2s?

**Comment by sam-goodwin** [comment]
for `JsonQueue<T>`, where should we place the parsed value?

```ts
interface SQSRecord<T> {
  body: string; // <- this is the vanilla AWS API
  value: T; // <- maybe we add a new field? Or should we override body?
}
```

**Comment by thantos** [comment]
Make it explicit to not polite the sfn state?

**Comment by sam-goodwin** [comment]
> Make it explicit to not polite the sfn state?

I don't know what you mean?

**Comment by sam-goodwin** [comment]
Hmm, if this is the interface
```ts
public forEach(
    handler: Function<SQSEvent<T>, lambda.SQSBatchResponse>,
    props?: aws_lambda_event_sources.SqsEventSourceProps
  ): void {
    handler.resource.addEventSource(
      new aws_lambda_event_sources.SqsEventSource(this.resource, props)
    );
  }
```

And we want to inject code that parses the body string, how would we inject that into the Function?

Should we instead change the interface to be

```ts
public forEach(scope: Construct, id: string, props: FunctionProps & SqsEventSourceProps, handle: (event: ..) => ..)
```

And then have the `forEach` instantiate the Function?

**Comment by sam-goodwin** [comment]
Yeah, I think this is better! We can provide an escape hatch if folk want to pass a pre-existing function

<img width="511" alt="image" src="https://user-images.githubusercontent.com/38672686/185725902-af6ce114-9cb4-4cff-88b1-fa843549cc42.png">

**Comment by thantos** [comment]
Looks good to me, and make the scope optional?

**Comment by sam-goodwin** [comment]
> Looks good to me, and make the scope optional?

Yep, even id can default to "forEach"

**Comment by sam-goodwin** [comment]
> > Looks good to me, and make the scope optional?
> 
> Yep, even id can default to "forEach"

Which would work in 99% of cases because it's not like you'd ever attach two consumers

**Comment by thantos** [comment]
```ts
const n = 0;
let name = "forEach";
do {
   const child = queue.node.tryFindChild(name)
   if(!child) {
       breakk
   }
  name = `forEach${++n}`;
} while(true);
```

**Comment by sam-goodwin** [comment]
> ```ts
> 
> let n = 0;
> 
> let name = "forEach";
> 
> do {
> 
>    const child = queue.node.tryFindChild(name);
> 
>    if(!child) {
> 
>       break;
> 
>    }
> 
>   name = `forEach${++n}`;
> 
> } while(true);
> 
> ```

Sure that would work. But it has risks because of you remove one in the middle they all change.

**Comment by thantos** [comment]
Uhhgg, yeah, good point. Lets enforce the singleton when the automatic name is used?
