### ISSUE TITLE
Step Functions: `undefined` vs `null`

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/functionless#78]
In Step Functions, we currently use `null` in places where we really mean `undefined` in TypeScript. This works for many cases but is definitely a gotcha that could hurt people. How do we model `undefined` in Step Functions?

An object with a missing is "undefined", but how do we return `undefined` as the whole result? We can't - only `null` can be returned.

**Comment by thantos** [comment]
#314 Decision was to fail on invalid undefined cases. Explicit null should be used during assignment.
